server:
  port: 8090

logging:
  level:
    org.spring.framework: DEBUG

spring:
  messages:
    basename: messages

  security:
    user:
      name: username
        password: passw0rd

management:
  endpoint:
    web:
      exposure:
        include: "*"

